Voyages/src/Entity/City.php
<?php

namespace App\Entity;

use App\Repository\CityRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ORM\Entity(repositoryClass=CityRepository::class)
 */
class City
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     * @Groups({"api_v1_city"})
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups({"api_v1_city"})
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups({"api_v1_city"})
     */
    private $country;

    /**
     * @ORM\Column(type="datetime")
     * @Groups({"api_v1_city"})
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updatedAt;

    /**
     * @ORM\Column(type="integer")
     * @Groups({"api_v1_city"})
     */
    private $geonameId;

    /**
     * @ORM\OneToMany(targetEntity=Review::class, mappedBy="city", orphanRemoval=true)
     */
    private $Reviews;

    /**
     * @ORM\ManyToMany(targetEntity=Tag::class, inversedBy="cities")
     */
    private $tags;

    /**
     * @ORM\OneToMany(targetEntity=CityLike::class, mappedBy="city", orphanRemoval=true)
     */
    private $cityLikes;

    public function __construct()
    {
        $this->Reviews = new ArrayCollection();
        $this->tags = new ArrayCollection();
        $this->cityLikes = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->name;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(string $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getGeonameId(): ?int
    {
        return $this->geonameId;
    }

    public function setGeonameId(int $geonameId): self
    {
        $this->geonameId = $geonameId;

        return $this;
    }

    /**
     * @return Collection|Review[]
     */
    public function getReviews(): Collection
    {
        return $this->Reviews;
    }

    public function addReview(Review $review): self
    {
        if (!$this->Reviews->contains($review)) {
            $this->Reviews[] = $review;
            $review->setCity($this);
        }

        return $this;
    }

    public function removeReview(Review $review): self
    {
        if ($this->Reviews->contains($review)) {
            $this->Reviews->removeElement($review);
            // set the owning side to null (unless already changed)
            if ($review->getCity() === $this) {
                $review->setCity(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Tag[]
     */
    public function getTags(): Collection
    {
        return $this->tags;
    }

    public function addTag(Tag $tag): self
    {
        if (!$this->tags->contains($tag)) {
            $this->tags[] = $tag;
            $tag->addCity($this);
        }

        return $this;
    }

    public function removeTag(Tag $tag): self
    {
        if ($this->tags->contains($tag)) {
            $this->tags->removeElement($tag);
            $tag->removeCity($this);
        }

        return $this;
    }

    /**
     * @return Collection|CityLike[]
     */
    public function getCityLikes(): Collection
    {
        return $this->cityLikes;
    }

    public function addCityLike(CityLike $cityLike): self
    {
        if (!$this->cityLikes->contains($cityLike)) {
            $this->cityLikes[] = $cityLike;
            $cityLike->setCity($this);
        }

        return $this;
    }

    public function removeCityLike(CityLike $cityLike): self
    {
        if ($this->cityLikes->contains($cityLike)) {
            $this->cityLikes->removeElement($cityLike);
            // set the owning side to null (unless already changed)
            if ($cityLike->getCity() === $this) {
                $cityLike->setCity(null);
            }
        }

        return $this;
    }

    /**
     * @Groups({"api_v1_city"})
     */
    public function getUrlCity()
    {
        return '/city/' . $this->getGeonameId();
        //return 'http://' . $_SERVER['SERVER_NAME'] . '/city/' . $this->getGeonameId();
    }


    public function isLikedByUser(User $user): bool
    {
        foreach ($this->cityLikes as $like) {
            if ($like->getUser() === $user) {
                return true;
            }
        }
        return false;
    }

}

Voyages/src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\Language;
use App\Entity\User;
use FOS\CKEditorBundle\Form\Type\CKEditorType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Image;
use Symfony\Component\Validator\Constraints\Length;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('firstname', TextType::class, [
                'label' => 'Prénom',
                'attr' => [ 'class' => 'form-group' ],
            ])
            ->add('name', TextType::class, [
                'label' => 'Nom',
            ])
            ->add('username', TextType::class, [
                'label' => 'Pseudo',
            ])
            ->add('email', EmailType::class, [
                'label' => 'Email',
                'disabled' => true,
            ])
            ->add('avatar', FileType::class, [
                'label' => 'Avatar',
                'mapped' => false,
                'constraints' => [
                    new Image([
                        'maxSize' => '1024k',
                        //'maxSizeMessage' => 'Fichier trop grand',
                    ])
                ]
            ])
            ->add('description', CKEditorType::class, [
                'label' => 'Présentation',
                'constraints' =>  [
                    new Length([
                        'min' => 25,
                        'max' => 2000,
                        'minMessage' => "{{ limit }} caractères minimum",
                        'maxMessage' => "{{ limit }} caractères maximum",
                        'allowEmptyString' => false,
                    ]),
                ]
            ])
            ->add('languages', EntityType::class, [
                'label' => 'Langues Parlées',
                'class' => Language::class,
                'choice_label' => 'name',
                'multiple' => true,
                'expanded' => true,
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => User::class,
            'attr' => [
                'novalidate' => 'novalidate', 
                'class' => 'd-flex flex-column justify-content-xl-center  justify-content-lg-center col-12 col-lg-12 col-xl-12',
            ],
        ]);
    }
}

Voyages/src/Controller/Api/V1/UserController.php
<?php

namespace App\Controller\Api\V1;

use App\Entity\User;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;



/**
 * @Route("/api/v1", name="api_v1_")
 */
class UserController extends AbstractController
{
    /**
     * @Route("/user/{id}", name="user_like", requirements={"id"="\d+"}, methods={"POST"})
     */
    public function userLike($id, UserRepository $userRepository)
    {
        //$id => liked user
        $userTarget = $this->getDoctrine()->getRepository(User::class)->find($id);

        $userSource = $this->getUser();

        if (!$userSource) {

            return $this->json(403);
        }
        $arrayLikers = [];


        foreach ($userTarget->getusers() as $userLike) {
            if ($userLike == $userSource) {
                $userSource->removeFavoriteUser($userTarget);
                $entityManager = $this->getDoctrine()->getManager();
                $entityManager->persist($userSource);
                $entityManager->flush();

                return $this->json([
                    'code' => 200,
                    'message' => ' unliked',
                ], 200);
            }
        }

        $userSource->addFavoriteUser($userTarget);
        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->persist($userSource);
        $entityManager->flush();

        return $this->json([
            'code' => 201,
            'message' => 'liked',

        ], 201);
    }


    /**
     * @Route("/user/{id}/report", name="user_report", requirements={"id"="\d+"}, methods={"POST"})
     */
    public function report($id)
    {

        $userRequest = $this->getUser();

        if (!$userRequest) {

            return $this->json(403);
        }

        $userToModerate = $this->getDoctrine()->getRepository(User::class)->find($id);
        $userToModerate->setIsReported(true);

        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->persist($userToModerate);
        $entityManager->flush();

        if ($userToModerate->GetIsReported() === true) {
            return new Response('Utilisateur signalé', Response::HTTP_ACCEPTED);
        }
    }

}

Voyages/src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\UserType;
use App\Form\Language;
use App\Repository\UserRepository;
use App\Service\ImageUploader;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/user")
 */
class UserController extends AbstractController
{
    /**
     * @Route("/", name="user_index", methods={"GET"})
     */
    public function index(UserRepository $userRepository): Response
    {
        return $this->render('user/index.html.twig', [
            'users' => $userRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="user_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $user = new User();
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($user);
            $entityManager->flush();

            return $this->redirectToRoute('user_index');
        }

        return $this->render('user/new.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="user_show", methods={"GET"})
     */
    public function show(User $user): Response
    {

        return $this->render('user/show.html.twig', [
            'user' => $user,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="user_edit", methods={"GET","POST"})
     */
    public function edit(ImageUploader $imageUploader, Request $request, User $user): Response
    {
        //teste le droit (edit) sur l'objet($user)
        $this->denyAccessUnlessGranted('edit', $user);

        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            if ($form->get('avatar')->getData()) {
                $fileName = $imageUploader->moveFile($form->get('avatar')->getData(), 'images/avatars');
                $user->setAvatar($fileName);
            }

            $this->getDoctrine()->getManager()->flush();

            $this->addFlash(
                'success',
                'Le profil a été mis à jour!'
            );

            return $this->redirectToRoute('user_show', ['id' => $user->getId()]);
        }

        return $this->render('user/edit.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="user_delete", methods={"DELETE"})
     */
    public function delete(Request $request, User $user): Response
    {
        if ($this->isCsrfTokenValid('delete' . $user->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($user);
            $entityManager->flush();
        }
        $this->get('security.token_storage')->setToken(null);
        $this->get('session')->invalidate();

        return $this->redirectToRoute('accueil');
    }
}

Voyages/templates/user/show_partials/left.html.twig
<div>
    <h3 class="title-badges">Badges obtenus &nbsp</h3>
    <div class="hide-scroll">
        <div class="box-badges">
            {% for badge in user.badges %}
            <p><img src="{{asset('images/badges/' ~ badge.filename ~ '.svg') }}" alt="Image de Paris"
                    class="img-badge" />
                <span class="text-thumb">{{ badge.name }}</span></p>
            {% endfor %}
        </div>
    </div>
</div>

<div>
    <h3 class="title-badges">Villes favorites &nbsp</h3>
    <div class="hide-scroll">
        <div class="box-badges">
            {% if user != app.user %}
            {% for cityLiked in user.cityLikes %}
            <p><a class="link-item-profile-box" href="{{ path('city_show', { geonameId: cityLiked.city.geonameId }) }}"><img src="{{asset('images/accueil/picture_' ~ random(1,17) ~ '.jpg') }}" alt=""
                    class="img-badge" />
                <span class="text-thumb">{{ cityLiked.city.name }}, {{ cityLiked.city.country }}</span></a></p>
            {% endfor %}
            {% else %}
            {% for cityLiked in app.user.cityLikes %}
            <p><a class="link-item-profile-box" href="{{ path('city_show', { geonameId: cityLiked.city.geonameId }) }}"><img src="{{asset('images/accueil/picture_' ~ random(1,17) ~ '.jpg') }}" alt=""
                    class="img-badge" />
                <span class="text-thumb">{{ cityLiked.city.name }}, {{ cityLiked.city.country }}</span></a></p>
            {% endfor %}
            {% endif %}
        </div>
    </div>
</div>

<div>
    {% if user != app.user %}
    <h3 class="title-badges">Langues parlées&nbsp</h3>
    <div class="hide-scroll">
        <div class="box-badges">
            {% for languages in user.languages %}
            <p><img src="{{asset('images/flags/' ~ languages.flag ) }}" alt="Icône drapeau"
                class="img-badge" />
            <span class="text-thumb">{{ languages }}</span></a></p>
            {% else %}
                <div class="alert alert-info small">Il n'y a pas de langues ajoutées.</div> 
            {% endfor %}
        </div>
    </div>
    {% else %}
    <h3 class="title-badges">Mes voyageurs favoris &nbsp</h3>
    <div class="hide-scroll">
        <div class="box-badges">
            {% for userLiked in app.user.favoriteUser %}
            <p><a class="link-item-profile-box" href="{{path('user_show', {id : userLiked.id })}}"><img src="{{asset('images/avatars/' ~ userLiked.avatar ) }}" alt="Image de profil de l'utilisateur {{ userLiked.username }}"
                class="img-badge" />
            <span class="text-thumb">{{ userLiked.username }}</span></a></p>
            {% else %}
            <div class="alert alert-info small">Il n'y a pas de voyageurs favoris.</div> 
        {% endfor %}
        </div>
    </div>
    {% endif %}
</div>

Voyages/templates/user/show_partials/right.html.twig
<div class="box-right-profile">
    <h3 class="title-badges">Photos postées &nbsp</h3>
    <div class="hide-scroll">
        <div class="box-badges box-gallery-right">
            <div class="city-pictures img-gallery">
                {% for row in user.reviews %}
                {% for image in row.pictures %}
                <p class="paragraph-inline"><img id="{{ 'image' ~ random(1,50000) }}"
                        src="{{asset('images/uploads/' ~ image.filename) }}" alt="Image de Paris"
                        class="img-carousel" /><span class="text-thumb">{{ image.title }}</span></p>
                {% endfor %}
                {% else %}
                    <div class="alert alert-info small">Il n'y a pas de contenu posté.</div> 
                {% endfor %}
            </div>
        </div>
    </div>
</div>

<!-- The Modal -->
<div id="myModal" class="modal">
    {# <span class="close">&times;</span> #}
    <img class="modal-content" id="img01">
    {#  <div id="caption"></div> #}
</div>

{% dump(user) %}